[build]
  command = "npm run build" # runs with ENV=production
  publish = "dist"

[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [ ".cache" ]

[[edge_functions]]
function = "eleventy-edge"
path = "/*"

[context.tutor-dev]
NODE_ENV="tutor-dev"
ELEVENTY_ENV="tutor-dev"

[context.tutor-local]
NODE_ENV="tutor-local"
ELEVENTY_ENV="tutor-local"

# Local dev settings
[dev]
  # framework = "#static"
  port=8888
  targetPort=4040

[context.dev.environment]
NODE_ENV="development"
ELEVENTY_ENV="development"

# Per-branch settings (except production)
[context.branch-deploy]
NODE_ENV="development"
ELEVENTY_ENV="development"
command = "cat ./custom-headers/_global ./custom-headers/_branch-deploy > ./public/_headers && npm run build"

# Deploy preview settings
[context.deploy-preview]
NODE_ENV="development"
ELEVENTY_ENV="development"
command = "cat ./custom-headers/_global ./custom-headers/_deploy-preview > ./public/_headers && npm run build"

[context.develop]
NODE_ENV="development"
ELEVENTY_ENV="development"
command = "cat ./custom-headers/_global ./custom-headers/_develop > ./public/_headers && npm run build"

[context.staging]
NODE_ENV="development"
ELEVENTY_ENV="development"
command = "cat ./custom-headers/_global ./custom-headers/_staging > ./public/_headers && npm run build"

# Production settings
[context.production]
NODE_ENV="production"
ELEVENTY_ENV="production"
command = "cat ./custom-headers/_global ./custom-headers/_production > ./public/_headers && npm run build"
