[build]
  command = "npm run build" # runs with ENV=production
  publish = "dist"

[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [ ".cache" ]

[[headers]]
  for = "/favicon/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
[[headers]]
  for = "/feeds/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
[[headers]]
  for = "/api/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
[[headers]]
  for = "/manifest.json"
    [headers.values]
    Access-Control-Allow-Origin = "*"
[[headers]]
  for = "*.js"
  [headers.values] # cache for 1 year
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.css"
  [headers.values] # cache for 1 year
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "/*.(svg|jpg|jpeg|png|gif|webp|ico|ttf|ttc|otf|eot|woff|woff2)"
  [headers.values] # cache for 1 year
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=31536000, immutable"
# TODO: disable indexing globally. Before production launch, we have to do this: https://docs.netlify.com/routing/headers/#custom-headers-for-different-branch-or-deploy-contexts
[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex"

[dev]
  # framework = "#static"
  port=8888
  targetPort=4040

[[edge_functions]]
function = "eleventy-edge"
path = "/*"

[context.tutor-dev]
NODE_ENV="development"
ELEVENTY_ENV="tutor-dev"

[context.tutor-local]
NODE_ENV="production"
ELEVENTY_ENV="tutor-local"
