name: Changed Data Files

on:
  push:
    branches:
      - develop
    paths:
      - 'src/data/**'

jobs:
  changed_files:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2  # OR "2" -> To retrieve the preceding commit.
          persist-credentials: true

      - name: Get changed data files
        id: changed-data-files
        uses: tj-actions/changed-files@v45
        with:
          # Avoid using single or double quotes for multiline patterns
          files: |
            src/data/**

      - name: List all changed data files
        if: steps.changed-data-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-data-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
