name: Changed Data Files - Develop

on:
  push:
    branches:
      - dev/test/api
    paths:
      - '.github/workflows/**'
      - 'src/_data/**.js'
      - 'src/_data/**.yml'
      - 'src/pages/api/**.njk'
      - 'src/_includes/modules/api-config.njk'

jobs:
  automatic-pr:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Automatic PR
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 10  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
      # NOTE: `since_last_remote_commit: true` is implied by default and falls back to the previous local commit.

      - name: List all changed files
        id: list-files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
      
      - name: Reset api/dev branch
        id: reset-branch
        run: |
          git fetch origin api/dev:api/dev
          git reset --hard api/dev

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7.0.5
        with:
          commit-message: automated change to update api/dev
          title: update api/dev
          body: Update update api/dev to reflect latest changes
          draft: true
          add-paths: |
            .github/workflows/*
            src/_data/*.js
            src/_data/*.yml
            src/pages/api/*.njk
            src/_includes/modules/api-config.njk
          branch: auto/api/dev
          base: api/dev


  # create_pr:
  #   runs-on: ubuntu-latest
  #   name: Create PR
  #   steps:
  #     - name: sparse checkout api/dev branch
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #         ref: api/dev
  #         sparse-checkout: |
  #           .github/workflows/**
  #           src/_data/**.js
  #           src/_data/**.yml
  #           src/pages/api/**.njk
  #           /src/_includes/modules/api-config.njk
  #         sparse-checkout-cone-mode: false
  #     - name: create temp branch
  #       uses: carlsberg/temporary-branch-action@1.1.3
  #       id: temp-branch
  #       with:
  #         base: api/dev
  #     - name: checkout specific files in develop branch
  #       run: |
  #         git checkout ${{ steps.temp-branch.outputs.branch }}
  #         git checkout develop -- .github/workflows/** src/_data/**.js src/_data/**.yml src/pages/api/**.njk /src/_includes/modules/api-config.njk
  #     - name: set datestamp
  #       id: datestamp
  #       run: |
  #         echo "datestamp=$(git log -1 --format=%cd --date=format:%Y-%m-%dh%H%M%S)" >> $GITHUB_OUTPUT
  #     - name: set PR message
  #       id: message
  #       run: |
  #         title="[Auto PR]: ${{ steps.datestamp.outputs.datestamp }} Update API - Dev"
  #         body="This PR was auto-generated on ${{ steps.datestamp.outputs.datestamp }} \
  #           by [create-pull-request](https://github.com/peter-evans/create-pull-request)."
  #         echo "title=$title" >> $GITHUB_OUTPUT
  #         echo "body=$body" >> $GITHUB_OUTPUT
  #     - name: Create Pull Request
  #       uses: peter-evans/create-pull-request@v7
  #       with:
  #         branch: auto/api/dev
  #         title: ${{ steps.message.outputs.title }}
  #         body: ${{ steps.message.outputs.body }}
