meta:
  id: COL-002
  title: "UX Design"
  topic: "UX"
  description: "Explore our free collection of UX courses, tutorials, webinars, articles, and jobs."
  slug: ux-design
  color: teal
  order: 4

card:
  description: "User experience can make or break a website. Let’s put yours to the test."

header:
  header_id: # default is null
  header_class: # default is null
  heading_type: h1 # h1-h6, default is h2
  heading_class: # default is caps
  heading_id: # default is null
  heading: UX Design
  description: |
    <p>Gymnasium offers free online <span class="no-wrap">UX <a href="#courses"><b>courses</b></a></span>, <a href="#tutorials"><b>tutorials</b></a>, <a href="#webinars"><b>webinars</b></a>, <a href="#articles"><b>articles</b></a>, and <a href="#jobs"><b><span class="visually-hidden">UX</span> jobs</b></a> through Aquent.</p>

courses:
  module: lists/image-course
  header:
    heading: "UX Courses"
    description: Learn UX design with industry experts from Capital One to <cite>The New York Times</cite>.
  cta:
    href: /courses/
    label: View More Courses
    class: btn
  ux-courses:
    schema: true
    ids:
    - id: GYM-103
    - id: GYM-014
    - id: GYM-015

tutorials:
  module: lists/image-course
  header:
    heading: "UX Tutorials"
    description: Learn a new UX skill in 5 minutes.
  cta:
    href: /courses/take5/
    label: View More Tutorials
    class: btn
  ux-tutorials:
    ids:
    - id: GYM-5061
    - id: GYM-5060
    - id: GYM-5059
    - id: GYM-5051
    - id: GYM-5050
    - id: GYM-5049

webinars:
  module: lists/image-course
  header:
    heading: UX Webinars
    description: Insightful conversations with trailblazers in the web community.
  cta:
    href: /webinars/
    label: View More Webinars
    class: btn
  ux-webinars:
    ids:
    - id: web-0013
    - id: web-0011
    - id: web-0010
    - id: web-0003
    - id: web-0002
    - id: web-0001

articles:
  module: lists/default
  header:
    heading: "UX Articles"
  ux:
    links:
    - href: "https://medium.com/gymnasium/from-filler-to-matter-wireframes-and-prototypes-in-ux-design-a73b0c0c27cd"
      label: "From Filler to Matter: Wireframes and Prototypes in UX Design"
    - href: "https://medium.com/gymnasium/the-dangers-of-generalism-in-ux-and-the-t-shaped-solution-72548bc67337"
      label: "Generalism in UX: It’s About Balance"
    - href: "https://medium.com/gymnasium/brad-frost-on-how-and-why-to-use-pattern-lab-49607f89d7f0"
      label: "Brad Frost on How (and Why) to Use Pattern Lab"
    - href: "https://medium.com/gymnasium/writing-meaningful-content-is-easier-than-you-think-45e0cb05dea6"
      label: "Writing Meaningful Content Is Easier Than You Think"
    - href: "https://medium.com/gymnasium/are-you-designing-for-real-people-or-just-personas-2ffdb6c3cd9b"
      label: "Are You Designing for Real People or Just Personas?"
    - href: "https://medium.com/gymnasium/https-medium-com-gymnasiumtweets-approaches-to-successful-rapid-prototyping-320361571f83"
      label: "Approaches to Successful Rapid Prototyping"
    - href: "https://medium.com/gymnasium/creating-a-vector-logo-in-sketch-3-6d67e72a1449"
      label: "Creating a Vector Logo in Sketch"

jobs:
  module: jobs
  roles:
    - ui-web-design
    # - user-experience
  heading: UX Jobs
